FROM jenkins/jenkins:lts

USER root

# Docker CLI + dependencies
RUN apt-get update && \
    apt-get install -y libatomic1 docker.io curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Optional but recommended for your pipeline deploy stage
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

USER jenkins